# Generated by Django 2.1.15 on 2020-05-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('useremail', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default=False, max_length=70)),
            ],
        ),
    ]
