# Generated by Django 4.0 on 2021-12-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=200)),
                ('useremail', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=70)),
                ('alert_options', models.CharField(choices=[('Daily', 'Daily'), ('Hourly', 'Hourly'), ('None', 'None')], default='Daily', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stockId', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='Manual', max_length=70)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('entry', models.FloatField(blank=True, default='', max_length=70)),
                ('stop', models.FloatField(blank=True, default='', max_length=70)),
                ('last_updated', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopwatchr.users')),
            ],
        ),
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopwatchr.stocks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopwatchr.users')),
            ],
        ),
    ]
