# Generated by Django 3.2.3 on 2021-06-01 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatchr', '0002_alter_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockId', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='Manual', max_length=70)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('entry', models.FloatField(blank=True, default='', max_length=70)),
                ('stop', models.FloatField(blank=True, default='', max_length=70)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopwatchr.users')),
            ],
        ),
    ]
